// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TaskList.Api.Data;

namespace TaskList.WebAPI.Migrations
{
    [DbContext(typeof(DataContext))]
    partial class DataContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.1-servicing-10028");

            modelBuilder.Entity("TaskList.Api.Model.Tasks", b =>
                {
                    b.Property<int>("TasksId")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("AssignedUserId");

                    b.Property<string>("CreationDate");

                    b.Property<string>("Description");

                    b.Property<string>("LastUpdateDateTime");

                    b.Property<int>("Priority");

                    b.Property<int>("Status");

                    b.Property<string>("Title");

                    b.HasKey("TasksId");

                    b.ToTable("Tasks");
                });
#pragma warning restore 612, 618
        }
    }
}
